=== kwakutwumasi/Quakearts-Code-Generator-Plugin/Quakearts Code Generators/src/com/quakearts/webtools/codegenerators/model/scaffolding.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://quakearts.com/scaffolding" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://quakearts.com/scaffolding">

    <element name="scaffolding">
    	<complexType>
    		<sequence>
    			<element name="properties" minOccurs="0" maxOccurs="1"
    				type="tns:scaffolding-properties">
    			</element>
    			<element name="template-group" minOccurs="1" maxOccurs="unbounded"
    				type="tns:template-group">
    			</element>
    			<element name="resource" minOccurs="1"
					maxOccurs="unbounded" type="tns:resource">
				</element>
    			<element name="folder-structure" minOccurs="1"
    				maxOccurs="1" type="tns:folder-structure">
    			</element>
    		</sequence>
    		<attribute name="id" type="string" use="required"></attribute>
    	</complexType>
    </element>

    <complexType name="folder">
    	<sequence>
            <element name="folder" type="tns:folder" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
        <attribute name="name" type="string" use="required"></attribute>
        <attribute name="folderID" type="string" use="required"></attribute>
    </complexType>
    
    <complexType name="folder-structure">
		<sequence>
			<element name="folder" type="tns:folder" minOccurs="1"
				maxOccurs="1">
			</element>
		</sequence>
	</complexType>
    
    <complexType name="beanType">
    	<simpleContent>
			<extension base="string">
				<attribute name="restriction-type" use="required">
					<simpleType>
						<restriction base="string">
							<enumeration value="MUSTBE"></enumeration>
							<enumeration value="CHILDOF"></enumeration>
							<enumeration value="HASMETHOD"></enumeration>
							<enumeration value="ANNOTATION"></enumeration>
							<enumeration value="NAMELIKE"></enumeration>
						</restriction>
					</simpleType>
				</attribute>
				<attribute name="exclusive" use="optional" type="boolean"></attribute>
			</extension>	
    	</simpleContent>
	</complexType>
	
	<complexType name="scaffolding-properties">
		<sequence>
			<element name="entry" maxOccurs="unbounded" minOccurs="1" type="tns:property-entry">
			</element>
		</sequence>
	</complexType>
	
	<complexType name="template-group">
		<sequence>
			<element name="template" minOccurs="1" maxOccurs="unbounded"
				type="tns:template">
			</element>
			<element name="bean" minOccurs="0"
				maxOccurs="unbounded" type="tns:bean">
			</element>
		</sequence>
		<attribute name="folderID"></attribute>
	</complexType>

	<complexType name="property-entry">
		<simpleContent>
			<extension base="string">
				<attribute name="property" use="required" type="string">
				</attribute>
			</extension>
		</simpleContent>
	</complexType>
	
	<complexType name="bean">
		<choice>
			<element name="bean-class" type="tns:beanType" minOccurs="1" maxOccurs="1">
			</element>
			<element name="bean-interface" type="tns:beanType" minOccurs="1" maxOccurs="1">
			</element>
		</choice>
	</complexType>
	
	<complexType name="resource">
		<attribute name="folderID" use="required" type="string"></attribute>
		<attribute name="location" type="string" use="required"></attribute>
		<attribute name="template" type="boolean" use="optional"></attribute>
		<attribute name="filename" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="template">
		<attribute name="filename" type="string" use="required"></attribute>
		<attribute name="location" type="string" use="required"></attribute>
	</complexType>
</schema>

=== kwakutwumasi/Quakearts-Code-Generator-Plugin/Quakearts Code Generators/src/com/quakearts/webtools/codegenerators/scaffolding/bean-forms-scaffolding.xml
<?xml version="1.0" encoding="UTF-8"?>
<scaffolding id="basic-app" xmlns="http://quakearts.com/scaffolding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://quakearts.com/scaffolding ../model/scaffolding.xsd ">
	<properties>
		<entry property="apptitle">Bean Application</entry>
		<entry property="company">Quake Arts Inc.</entry>
	</properties>
	<template-group folderID="tm">
		<template filename="crud.xhtml" location="basic/crud.xhtml" />
	</template-group>
	<resource folderID="images" location="crudapp/images/loading.gif" />
	<resource folderID="images" location="crudapp/images/loading-small.gif" />
	<resource folderID="beans" location="basic/crudappapplicationbean.vm" filename="CRUDApplicationBean.java" template="true" />
	<resource folderID="web" location="crudapp/index.vm" filename="index.jsp" template="true" />
	<resource folderID="webinf" location="crudapp/web.xml" template="true" filename="web.xml" />
	<resource folderID="base" location="crudapp/template.xhtml" template="true" />
	<resource folderID="webinf" location="crudapp/faces-config.xml" />
	<folder-structure>
		<folder name="Root Folder" folderID="root">
			<folder name="src" folderID="src">
				<folder folderID="com" name="com">
					<folder folderID="quakearts" name="quakearts">
						<folder folderID="webapp" name="webapp">
							<folder folderID="beans" name="beans" />
						</folder>
					</folder>
				</folder>
			</folder>
			<folder name="WebContent" folderID="web">
				<folder name="base" folderID="base" />
				<folder name="resources" folderID="resources">
					<folder name="images" folderID="images" />
				</folder>
				<folder name="WEB-INF" folderID="webinf">
					<folder name="classes" folderID="classes" />
				</folder>
				<folder name="ui" folderID="ui" />
				<folder name="tm" folderID="tm" />
			</folder>
		</folder>
	</folder-structure>
</scaffolding>

=== kwakutwumasi/Quakearts-Code-Generator-Plugin/Quakearts Code Generators/src/com/quakearts/tools/web/generator/scaffolding/bean-forms-scaffolding.xml
<?xml version="1.0" encoding="UTF-8"?>
<scaffolding id="basic-app" xmlns="http://quakearts.com/scaffolding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://quakearts.com/scaffolding ../../model/scaffolding.xsd ">
	<properties>
		<entry displayName="Application Title" property="apptitle">Bean Application</entry>
		<entry displayName="Company" property="company">Quake Arts Inc.</entry>
		<entry displayName="CRUD Managed Bean Class Name" property="crudappClassName">CRUDApplicationBean</entry>
		<entry displayName="CRUD Managed Bean Name" property="crudappBeanName">crudapp</entry>
	</properties>
	<template-group folderID="cp">
		<template filename="@{beanName}.crud.xhtml" location="basic/crud.xhtml" />
	</template-group>
	<template-group folderID="beans">
		<template location="basic/finder.vm" filename="@{beanClassSimpleName}Finder.java"/>
		<template location="crudapp/dropdownhelper.vm" filename="@{beanClassSimpleName}DropdownHelper.java"/>
		<template location="crudapp/page.vm" filename="@{beanClassSimpleName}Page.java"/>
	</template-group>
	<resource folderID="images" location="crudapp/images/loading.gif" />
	<resource folderID="images" location="crudapp/images/loading-small.gif" />
	<resource folderID="beans" location="crudapp/crudappapplicationbean.vm" filename="@{crudappClassName}.java" template="true" />
	<resource folderID="webinf" location="crudapp/web.xml" template="true" filename="web.xml" />
	<resource folderID="base" location="crudapp/template.xhtml" template="true" />
	<resource folderID="webinf" location="crudapp/faces-config.xml" />
	<folder-structure>
		<folder name="Root Folder" folderID="root">
			<folder name="src" folderID="src">
				<folder name="main" folderID="main">
					<folder name="java" folderID="java">
						<folder folderID="com" name="com">
							<folder folderID="quakearts" name="quakearts">
								<folder folderID="webapp" name="webapp">
									<folder folderID="beans" name="beans" />
								</folder>
							</folder>
						</folder>
					</folder>
				</folder>
			</folder>
			<folder name="WebContent" folderID="web">
				<folder name="base" folderID="base" />
				<folder name="resources" folderID="resources">
					<folder name="images" folderID="images" />
				</folder>
				<folder name="WEB-INF" folderID="webinf">
					<folder name="classes" folderID="classes" />
				</folder>
				<folder name="ui" folderID="ui" />
				<folder name="cp" folderID="cp" />
			</folder>
		</folder>
	</folder-structure>
</scaffolding>

=== kwakutwumasi/Quakearts-Code-Generator-Plugin/Quakearts Code Generators/scaffolding.xml
<?xml version="1.0" encoding="UTF-8"?>
<scaffolding id="" xmlns="http://quakearts.com/scaffolding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://quakearts.com/scaffolding src/com/quakearts/tools/web/model/scaffolding.xsd ">
	<properties>
		<entry property="testproperty"><![CDATA[
			<test></test>
			<hibernate></hibernate>
		]]></entry>
	</properties>
	<template-group folderID="tm">
		<template filename="crud.xhtml" location="crudapp/basic.crud.xhtml" />
		<template filename="list.xhtml" location="crudapp/basic.list.xhtml" />
	</template-group>
	<resource folderID="images" location="crudapp/images/loading.gif" />
	<resource folderID="images" location="crudapp/images/loading-small.gif" />
	<resource folderID="ui" location="crudapp/view.xhtml" template="true" />
	<resource folderID="ui" location="crudapp/edit.xhtml" template="true" />
	<resource folderID="src" location="crudapp/"/>
	<folder-structure>
		<folder name="Root Folder" folderID="root">
			<folder name="src" folderID="src">
			</folder>
			<folder name="WebContent" folderID="web">
				<folder name="base" folderID="base" />
				<folder name="resources" folderID="resources">
					<folder name="images" folderID="images" />
				</folder>
				<folder name="WEB-INF" folderID="webinf">
					<folder name="classes" folderID="classes" />
				</folder>
				<folder name="ui" folderID="ui" />
				<folder name="tm" folderID="tm" />
			</folder>
		</folder>
	</folder-structure>
</scaffolding>

=== kwakutwumasi/Quakearts-Code-Generator-Plugin/Quakearts Code Generators/src/com/quakearts/tools/web/generator/scaffolding/bean-forms-partial.xml
<?xml version="1.0" encoding="UTF-8"?>
<scaffolding id="basic-app" xmlns="http://quakearts.com/scaffolding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://quakearts.com/scaffolding ../model/scaffolding.xsd ">
	<properties>
		<entry displayName="CRUD Managed Bean Class Name" property="crudappClassName">CRUDApplicationBean</entry>
		<entry displayName="CRUD Managed Bean Name" property="crudappBeanName">crudapp</entry>
	</properties>
	<template-group folderID="cp">
		<template filename="@{beanName}.crud.xhtml" location="basic/crud.xhtml" />
	</template-group>
	<template-group folderID="beans">
		<template location="basic/finder.vm" filename="@{beanClassSimpleName}Finder.java"/>
		<template location="crudapp/dropdownhelper.vm" filename="@{beanClassSimpleName}DropdownHelper.java"/>
		<template location="crudapp/page.vm" filename="@{beanClassSimpleName}Page.java"/>
	</template-group>
	<resource folderID="beans" location="crudapp/crudappapplicationbean.vm" filename="@{crudappClassName}.java" template="true" />
	<folder-structure>
		<folder name="Root Folder" folderID="root">
			<folder name="src" folderID="src">
				<folder folderID="com" name="com">
					<folder folderID="quakearts" name="quakearts">
						<folder folderID="webapp" name="webapp">
							<folder folderID="beans" name="beans" />
						</folder>
					</folder>
				</folder>
			</folder>
			<folder name="WebContent" folderID="web">
				<folder name="cp" folderID="cp" />
			</folder>
		</folder>
	</folder-structure>
</scaffolding>

=== kwakutwumasi/Quakearts-Code-Generator-Plugin/Quakearts Code Generators/src/com/quakearts/tools/web/generator/scaffolding/hibernate-crudapp-partial.xml
<?xml version="1.0" encoding="UTF-8"?>
<scaffolding id="hibernate-app-partial" xmlns="http://quakearts.com/scaffolding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://quakearts.com/scaffolding ../model/scaffolding.xsd ">
	<template-group folderID="cp">
		<template filename="@{beanName}.crud.xhtml" location="crudapp/crud.xhtml" />
	</template-group>
	<template-group folderID="ui">
		<template filename="@{beanName}.create.xhtml" location="crudapp/create.xhtml" />
		<template filename="@{beanName}.list.xhtml" location="crudapp/list.xhtml" />
	</template-group>
	<template-group folderID="beans">
		<template location="crudapp/finder.vm" filename="@{beanClassSimpleName}Finder.java"/>
		<template location="crudapp/dropdownhelper.vm" filename="@{beanClassSimpleName}DropdownHelper.java"/>
		<template location="crudapp/page.vm" filename="@{beanClassSimpleName}Page.java"/>
	</template-group>
	<folder-structure>
		<folder name="Root Folder" folderID="root">
			<folder name="src" folderID="src">
				<folder name="main" folderID="main">
					<folder name="java" folderID="java">
						<folder folderID="com" name="com">
							<folder folderID="quakearts" name="quakearts">
								<folder folderID="webapp" name="webapp">
									<folder folderID="beans" name="beans" />
								</folder>
							</folder>
						</folder>
					</folder>
				</folder>
			</folder>
			<folder name="WebContent" folderID="web">
				<folder name="ui" folderID="ui" />
				<folder name="cp" folderID="cp" />
			</folder>
		</folder>
	</folder-structure>
</scaffolding>

=== kwakutwumasi/Quakearts-Code-Generator-Plugin/Quakearts Code Generators/src/com/quakearts/webtools/codegenerators/scaffolding/secure-hibernate-crudapp-scaffolding.xml
<?xml version="1.0" encoding="UTF-8"?>
<scaffolding id="hibernate-app" xmlns="http://quakearts.com/scaffolding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://quakearts.com/scaffolding ../model/scaffolding.xsd ">
	<properties>
		<entry property="apptitle">Database Application</entry>
		<entry property="company">Quake Arts Inc.</entry>
		<entry property="jndiname">CRUDDB</entry>
		<entry property="datasourcetype">sqlserver</entry>
		<entry property="serverName">localhost</entry>
		<entry property="databaseName">master</entry>
		<entry property="user">sa</entry>
		<entry property="password">12345</entry>
		<entry property="serverPort"></entry>
		<entry property="createrole">CreateRole</entry>
		<entry property="deleterole">DeleteRole</entry>
		<entry property="readrole">ReadRole</entry>
		<entry property="updaterole">UpdateRole</entry>
		<entry property="loginmodule"><![CDATA[
			<login-module code="" flag="required">
				<module-option name=""></module-option>
				<module-option name=""></module-option>
				<module-option name=""></module-option>
			</login-module>
		]]></entry>
	</properties>
	<template-group folderID="tm">
		<template filename="crud.xhtml" location="crudapp/crud.xhtml" />
		<template filename="create.xhtml" location="crudappsecure/create.xhtml" />
		<template filename="list.xhtml" location="crudappsecure/list.xhtml" />
	</template-group>
	<resource folderID="images" location="crudapp/images/loading.gif" />
	<resource folderID="images" location="crudapp/images/loading-small.gif" />
	<resource folderID="beans" location="crudapp/crudappapplicationbean.vm" filename="CRUDApplicationBean.java" template="true" />
	<resource folderID="web" location="crudapp/index.vm" filename="index.jsp" template="true" />
	<resource folderID="webinf" location="crudappsecure/web.xml" template="true" filename="web.xml" />
	<resource folderID="webinf" location="crudapp/app-xa-ds.xml" template="true" />
	<resource folderID="webinf" location="crudappsecure/crudapp.login-jboss-beans.xml" template="true" />
	<resource folderID="webinf" location="crudapp/faces-config.xml" />
	<resource folderID="base" location="crudappsecure/template.xhtml" template="true" />
	<resource folderID="ui" location="crudapp/main.xhtml" template="true" />
	<folder-structure>
		<folder name="Root Folder" folderID="root">
			<folder name="src" folderID="src">
				<folder folderID="com" name="com">
					<folder folderID="quakearts" name="quakearts">
						<folder folderID="webapp" name="webapp">
							<folder folderID="beans" name="beans" />
						</folder>
					</folder>
				</folder>
			</folder>
			<folder name="WebContent" folderID="web">
				<folder name="base" folderID="base" />
				<folder name="resources" folderID="resources">
					<folder name="images" folderID="images" />
				</folder>
				<folder name="WEB-INF" folderID="webinf">
					<folder name="classes" folderID="classes" />
				</folder>
				<folder name="ui" folderID="ui" />
				<folder name="tm" folderID="tm" />
			</folder>
		</folder>
	</folder-structure>
</scaffolding>

=== kwakutwumasi/Quakearts-Code-Generator-Plugin/Quakearts Code Generators/src/com/quakearts/webtools/codegenerators/scaffolding/hibernate-crudapp-scaffolding.xml
<?xml version="1.0" encoding="UTF-8"?>
<scaffolding id="hibernate-app" xmlns="http://quakearts.com/scaffolding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://quakearts.com/scaffolding ../model/scaffolding.xsd ">
	<properties>
		<entry displayName="Application Title" property="apptitle">Database Application</entry>
		<entry displayName="Company" property="company">Quake Arts Inc.</entry>
		<entry displayName="CRUD Managed Bean Class Name" property="crudappClassName">CRUDApplicationBean</entry>
		<entry displayName="CRUD Managed Bean Name" property="crudappBeanName">crudapp</entry>
	</properties>
	<template-group folderID="tm">
		<template filename="@{beanName}.crud.xhtml" location="crudapp/crud.xhtml" />
		<template filename="@{beanName}.create.xhtml" location="crudapp/create.xhtml" />
		<template filename="@{beanName}.list.xhtml" location="crudapp/list.xhtml" />
	</template-group>
	<resource folderID="images" location="crudapp/images/loading.gif" />
	<resource folderID="images" location="crudapp/images/loading-small.gif" />
	<resource folderID="beans" location="crudapp/crudappapplicationbean.vm" filename="@{crudappClassName}.java" template="true" />
	<resource folderID="web" location="crudapp/index.vm" filename="index.jsp" template="true" />
	<resource folderID="webinf" location="crudapp/web.xml" template="true" filename="web.xml" />
	<resource folderID="webinf" location="crudapp/faces-config.xml" />
	<resource folderID="base" location="crudapp/template.xhtml" template="true" />
	<resource folderID="ui" location="crudapp/main.xhtml" template="true" />
	<folder-structure>
		<folder name="Root Folder" folderID="root">
			<folder name="src" folderID="src">
				<folder folderID="com" name="com">
					<folder folderID="quakearts" name="quakearts">
						<folder folderID="webapp" name="webapp">
							<folder folderID="beans" name="beans" />
						</folder>
					</folder>
				</folder>
			</folder>
			<folder name="WebContent" folderID="web">
				<folder name="base" folderID="base" />
				<folder name="resources" folderID="resources">
					<folder name="images" folderID="images" />
				</folder>
				<folder name="WEB-INF" folderID="webinf">
					<folder name="classes" folderID="classes" />
				</folder>
				<folder name="ui" folderID="ui" />
				<folder name="tm" folderID="tm" />
			</folder>
		</folder>
	</folder-structure>
</scaffolding>

=== kwakutwumasi/Quakearts-Code-Generator-Plugin/Quakearts Code Generators/src/com/quakearts/tools/web/generator/scaffolding/secure-hibernate-crudapp-partial.xml
<?xml version="1.0" encoding="UTF-8"?>
<scaffolding id="secure-hibernate-app-partial" xmlns="http://quakearts.com/scaffolding"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://quakearts.com/scaffolding ../model/scaffolding.xsd ">
	<properties>
		<entry displayName="Application Title" property="apptitle">Bean Application</entry>
		<entry displayName="Company" property="company">Quake Arts Inc.</entry>
		<entry displayName="CRUD Managed Bean Class Name" property="crudappClassName">CRUDApplicationBean</entry>
		<entry displayName="CRUD Managed Bean Name" property="crudappBeanName">crudapp</entry>	
		<entry displayName="Create Role" property="createrole">Create</entry>
		<entry displayName="Update Role" property="updaterole">Update</entry>
		<entry displayName="Read Role" property="readrole">Read</entry>
		<entry displayName="Delete Role" property="deleterole">Delete</entry>
	</properties>
	<template-group folderID="cp">
		<template filename="@{beanName}.crud.xhtml" location="crudapp/crud.xhtml" />
	</template-group>
	<template-group folderID="ui">
		<template filename="@{beanName}.create.xhtml" location="crudappsecure/create.xhtml" />
		<template filename="@{beanName}.list.xhtml" location="crudappsecure/list.xhtml" />
	</template-group>
	<template-group folderID="beans">
		<template location="crudapp/finder.vm" filename="@{beanClassSimpleName}Finder.java"/>
		<template location="crudapp/dropdownhelper.vm" filename="@{beanClassSimpleName}DropdownHelper.java"/>
		<template location="crudapp/page.vm" filename="@{beanClassSimpleName}Page.java"/>
	</template-group>
	<resource folderID="beans" location="crudapp/crudappapplicationbean.vm" filename="@{crudappClassName}.java" template="true" />
	<folder-structure>
		<folder name="Root Folder" folderID="root">
			<folder name="src" folderID="src">
				<folder name="main" folderID="main">
					<folder name="java" folderID="java">
						<folder folderID="com" name="com">
							<folder folderID="quakearts" name="quakearts">
								<folder folderID="webapp" name="webapp">
									<folder folderID="beans" name="beans" />
								</folder>
							</folder>
						</folder>
					</folder>
				</folder>
			</folder>
			<folder name="WebContent" folderID="web">
				<folder name="ui" folderID="ui" />
				<folder name="cp" folderID="cp" />
			</folder>
		</folder>
	</folder-structure>
</scaffolding>
